version: '3.8'

volumes:
    autodiller-db-data:
    autodiller-db-sqls:

services:
    postgres:
        build: ./db
        container_name: autodiller-db
        restart: always
        environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=autodiller_salon
        logging:
            driver: "json-file"
            options:
                max-size: 20m
                max-file: "5"
                labels: "production_status"
        labels:
            production_status: "testing"
        ports:
         - '5433:5432'
        volumes:
         # store data from the database
         - autodiller-db-data:/var/lib/postgresql/data
         # put sql scripts for any 
         - autodiller-db-sqls:/root/sql_dmls
